
- ros_topic_name: "/rov1/camera"
  gz_topic_name: "/world/bluerov2_pool_sim/model/rov1/link/base_link/sensor/camera_sensor/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "/rov1/imu"
  gz_topic_name: "/world/bluerov2_pool_sim/model/rov1/link/base_link/sensor/compass_sensor/magnetometer"
  ros_type_name: "sensor_msgs/msg/MagneticField"
  gz_type_name: "gz.msgs.Magnetometer"
  direction: GZ_TO_ROS

- ros_topic_name: "/rov1/magnetometer"
  gz_topic_name: "/world/bluerov2_pool_sim/model/rov1/link/base_link/sensor/imu_sensor/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS

- ros_topic_name: "/rov2/camera"
  gz_topic_name: "/world/bluerov2_pool_sim/model/rov2/link/base_link/sensor/camera_sensor/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "/rov2/imu"
  gz_topic_name: "/world/bluerov2_pool_sim/model/rov2/link/base_link/sensor/compass_sensor/magnetometer"
  ros_type_name: "sensor_msgs/msg/MagneticField"
  gz_type_name: "gz.msgs.Magnetometer"
  direction: GZ_TO_ROS

- ros_topic_name: "/rov2/magnetometer"
  gz_topic_name: "/world/bluerov2_pool_sim/model/rov2/link/base_link/sensor/imu_sensor/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS