
- ros_topic_name: "/rov1/camera"
  gz_topic_name: "/world/bluerov2_pool_sim/model/rov1/link/base_link/sensor/camera_sensor/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "/rov1/magnetic_field"
  gz_topic_name: "/world/bluerov2_pool_sim/model/rov1/link/base_link/sensor/compass_sensor/magnetometer"
  ros_type_name: "sensor_msgs/msg/MagneticField"
  gz_type_name: "gz.msgs.Magnetometer"
  direction: GZ_TO_ROS

- ros_topic_name: "/rov1/imu"
  gz_topic_name: "/world/bluerov2_pool_sim/model/rov1/link/base_link/sensor/imu_sensor/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS

- ros_topic_name: "/rov1/pressure"
  gz_topic_name: "/world/bluerov2_pool_sim/model/rov1/link/base_link/sensor/pressure_sensor/pressure"
  ros_type_name: "sensor_msgs/msg/FluidPressure"
  gz_type_name: "gz.msgs.FluidPressure"
  direction: GZ_TO_ROS

- ros_topic_name: "/rov1/thruster1/cmd_thrust"
  gz_topic_name: "/model/rov1/joint/thruster1_joint/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/rov1/thruster2/cmd_thrust"
  gz_topic_name: "/model/rov1/joint/thruster2_joint/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/rov1/thruster3/cmd_thrust"
  gz_topic_name: "/model/rov1/joint/thruster3_joint/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/rov1/thruster4/cmd_thrust"
  gz_topic_name: "/model/rov1/joint/thruster4_joint/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/rov1/thruster5/cmd_thrust"
  gz_topic_name: "/model/rov1/joint/thruster5_joint/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/rov1/thruster6/cmd_thrust"
  gz_topic_name: "/model/rov1/joint/thruster6_joint/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/rov2/camera"
  gz_topic_name: "/world/bluerov2_pool_sim/model/rov2/link/base_link/sensor/camera_sensor/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "/rov2/magnetic_field"
  gz_topic_name: "/world/bluerov2_pool_sim/model/rov2/link/base_link/sensor/compass_sensor/magnetometer"
  ros_type_name: "sensor_msgs/msg/MagneticField"
  gz_type_name: "gz.msgs.Magnetometer"
  direction: GZ_TO_ROS

- ros_topic_name: "/rov2/imu"
  gz_topic_name: "/world/bluerov2_pool_sim/model/rov2/link/base_link/sensor/imu_sensor/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS

- ros_topic_name: "/rov2/pressure"
  gz_topic_name: "/world/bluerov2_pool_sim/model/rov2/link/base_link/sensor/pressure_sensor/pressure"
  ros_type_name: "sensor_msgs/msg/FluidPressure"
  gz_type_name: "gz.msgs.FluidPressure"
  direction: GZ_TO_ROS

- ros_topic_name: "/rov2/thruster1/cmd_thrust"
  gz_topic_name: "/model/rov2/joint/thruster1_joint/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/rov2/thruster2/cmd_thrust"
  gz_topic_name: "/model/rov2/joint/thruster2_joint/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/rov2/thruster3/cmd_thrust"
  gz_topic_name: "/model/rov2/joint/thruster3_joint/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/rov2/thruster4/cmd_thrust"
  gz_topic_name: "/model/rov2/joint/thruster4_joint/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/rov2/thruster5/cmd_thrust"
  gz_topic_name: "/model/rov2/joint/thruster5_joint/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/rov2/thruster6/cmd_thrust"
  gz_topic_name: "/model/rov2/joint/thruster6_joint/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
